image: gitpod/workspace-full

# Commands that will run on workspace start
tasks:
    - name: Install genezio
      before: npm install -g genezio@latest
      command: genezio --version 
ports:
    - port: 5173-8300
      onOpen: ignore
      visibility: public
